feature/SM-5733: filter work updates by workstream & update id
departmentfortransport/street-manager-reporting-client pull request #130
Opened 2020-11-25 15:21 UTC by ccurran01

## Description

Add workstream prefix and update id as optional paramaters on the GetWorkUpdateRequest. 

## Coding Standards

Style guide: https://github.com/departmentfortransport/street-manager/wiki/Street-Manager-Style-Guide
Coding best practices: https://github.com/departmentfortransport/street-manager/wiki/Street-Manager-Coding-Best-Practices

## Checklist

- [ ] Branch named {feature|hotfix|task}/{SM-.*}
- [ ] If your pull request depends on any other, please link them
- [ ] Changes approved by your team
- [ ] Changes approved by another team
- [ ] API definitions updated
- [ ] Commit messages are meaningful
- [ ] Int UI tests passing https://circleci.com/gh/departmentfortransport/street-manager-int/tree/master
- [ ] Add `DO NOT MERGE` if you want to postpone merge

2020-11-27 10:41 UTC, cpaul92 approved these changes

2020-11-30 10:59 UTC, RichardEustace requested changes

2020-11-30 10:59 UTC, RichardEustace commented on src/interfaces/getWorksUpdatesRequest.ts
> +  workstream_prefix?: string
Should this not be an array?

2020-12-01 09:54 UTC, RichardEustace approved these changes

2020-12-04 13:58 UTC, merged